# coding: utf-8

"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.18.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.tracked_time import TrackedTime  # noqa: E501
from swagger_client.rest import ApiException


class TestTrackedTime(unittest.TestCase):
    """TrackedTime unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTrackedTime(self):
        """Test TrackedTime"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.tracked_time.TrackedTime()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
