# coding: utf-8

"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.18.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.git_entry import GitEntry  # noqa: E501
from swagger_client.rest import ApiException


class TestGitEntry(unittest.TestCase):
    """GitEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGitEntry(self):
        """Test GitEntry"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.git_entry.GitEntry()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
