FROM registry.fedoraproject.org/fedora:latest

RUN set -eux pipefail; dnf -y upgrade; dnf -y install pipx; PIPX_BIN_DIR=/usr/bin/ pipx install poetry

COPY . /src/
WORKDIR /src/

RUN set -eux pipefail; poetry install

EXPOSE 8000
ENTRYPOINT poetry run app
HEALTHCHECK --interval=5s --timeout=1s CMD curl http://localhost:8000/hook
